server:
  port: 8181
  servlet:
    context-path: /playerzen

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/playerzen
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 6pEvtOU5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB

files:
  storepath:
    storage:  "D:\\PlayerZenStorage"