server:
  servlet:
    context-path: /kinozen

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kinozen?useUnicode=true&characterEncoding=utf8
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: se1234

jpa:
  database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  show-sql: false

files:
  storepath:
    video_download:  "C:\\video_download"