server:
  servlet:
    context-path: /kinozen

spring:
  datasource:
    url: jdbc:postgresql://192.168.0.10:5432/kinozen?useUnicode=true&characterEncoding=utf8
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
    hibernate:
      ddl-auto: none


files:
  storepath:
    video_download:  "C:\\video_download"

